# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

apiVersion: flowconfig.intel.com/v1
kind: FlowConfigNodeAgentDeployment
metadata:
  labels:
    control-plane: flowconfig-daemon
  name: flowconfig-daemon-flowconfig-daemon
  namespace: intel-ethernet-operator-system
spec:
  DCFVfPoolName: intel.com/cvl_uft_admin
  NADAnnotation: sriov-cvl0-admin
