# permissions for end users to view ethernetclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ethernetclusterconfig-viewer-role
rules:
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ethernet.intel.com
  resources:
  - ethernetclusterconfigs/status
  verbs:
  - get
