# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

# permissions for end users to view flowconfignodeagentdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flowconfignodeagentdeployment-viewer-role
rules:
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flowconfig.intel.com
  resources:
  - flowconfignodeagentdeployments/status
  verbs:
  - get
