# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2022 Intel Corporation

apiVersion: ethernet.intel.com/v1
kind: EthernetNodeConfig
metadata:
  name: ethernetnodeconfig-sample
spec:
  # Add fields here
  foo: bar
